### ISSUE TITLE
Compass-generated CSS files don't trigger reload

### ISSUE THREAD

**Issue by deisner** [guard/guard-livereload#105]
I'm using
```
guard (2.6.0)
guard-compass (1.1.0)
guard-livereload (2.1.2)
```
When I make a change to a sass file (.scss), guard detects the change, runs compass via the guard-compass plugin-in, and updates the.css files. However, those CSS files aren't causing Chrome to actually reload the page. If I manually `touch` the .css file, the reload *does* happen.

After some digging around, I think I know what's going on. Commit [e20657](https://github.com/guard/guard-livereload/commit/e20657df1d2f6c05b9ddb5a98177f8fc8c1cdfbe) changed guard-livereload so that it uses `run_on_modifications` rather than `run_on_changes`. When compass is run, the original .css file is apparently deleted and then regenerated. I can tell this is so because `ls -i` shows the .css file has a new inode. You can also see it in the guard debugging output -- note that guard is trying to call the `run_on_changes` hook:

```
13:18:17 - DEBUG - Stop interactor
13:18:17 - DEBUG - Trying to run Guard::Compass#run_on_modifications with ["sass/variables/_colors.scss", "sass/variables/_colors.scss"]
13:18:17 - DEBUG - Trying to run Guard::Compass#run_on_changes with ["sass/variables/_colors.scss", "sass/variables/_colors.scss"]
13:18:17 - DEBUG - Hook :run_on_change_begin executed for Guard::Compass
overwrite css/calce-omega.styles.css
identical css/calce-omega.normalize.css
unchanged sass/calce-omega.hacks.scss
overwrite css/calce-omega.no-query.css
13:18:19 - DEBUG - Hook :run_on_change_end executed for Guard::Compass
13:18:19 - DEBUG - Start interactor
13:18:19 - DEBUG - Stop interactor
13:18:19 - DEBUG - Trying to run Guard::LiveReload#run_on_additions with ["css/calce-omega.no-query.css", "css/calce-omega.styles.css"]
13:18:19 - DEBUG - Trying to run Guard::LiveReload#run_on_changes with ["css/calce-omega.no-query.css", "css/calce-omega.styles.css"]
13:18:19 - DEBUG - Trying to run Guard::LiveReload#run_on_change with ["css/calce-omega.no-query.css", "css/calce-omega.styles.css"]
13:18:19 - DEBUG - Start interactor
```

When I `touch` the .css file (i.e. `$ touch css/calce-omega.styles.css`), the mtime is updated and then guard-livereload runs (via the `run_on_modifications` hook) and Chrome reloads the page. Here's the guard debugging output:

```
13:37:19 - DEBUG - Stop interactor
13:37:19 - DEBUG - Hook :run_on_modifications_begin executed for Guard::LiveReload
13:37:19 - INFO - Reloading browser: css/calce-omega.styles.css
13:37:19 - DEBUG - {:command=>"reload", :path=>"/path_to/calce_omega/css/calce-omega.styles.css", :liveCSS=>true}
13:37:19 - DEBUG - Hook :run_on_modifications_end executed for Guard::LiveReload
13:37:19 - DEBUG - Start interactor
```

I'm not entirely sure why the change was made, but I think this is not the expected behavior. I'm kind of new to this, though, so I may be missing something.

**Comment by e2** [comment]
Both Guard and Listen gems have been updated since. 

I believe this is fixed. It's best to use `Listen` 3.x to make sure.

If there are still problems - please open a new issue, thanks!
