### ISSUE TITLE
Livereload not detect modified files

### ISSUE THREAD

**Issue by argordmel** [guard/guard-livereload#115]
Hi guys!

i init the guard, but not reload browser.

Worked fine before, now that is not passed.

![guard_1](https://cloud.githubusercontent.com/assets/1320168/3541212/3590d612-084a-11e4-817a-a3506fd53f3d.png)

![guard_2](https://cloud.githubusercontent.com/assets/1320168/3541214/3c20ed82-084a-11e4-9ea5-32b9d551d29e.png)

My PC
S.O. Ubuntu 14.04 64bits
Ruby: ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

Gemfle.lock

GEM
  specs:
    celluloid (0.15.2)
      timers (~> 1.1.0)
    celluloid-io (0.15.0)
      celluloid (>= 0.15.0)
      nio4r (>= 0.5.0)
    coderay (1.1.0)
    em-websocket (0.5.0)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.5.3)
    eventmachine (1.0.3)
    ffi (1.9.3)
    formatador (0.2.4)
    guard (2.6.0)
      formatador (>= 0.2.4)
      listen (~> 2.7)
      lumberjack (~> 1.0)
      pry (>= 0.9.12)
      thor (>= 0.18.1)
    guard-livereload (2.3.0)
      em-websocket (~> 0.5)
      guard (~> 2.0)
      multi_json (~> 1.8)
    http_parser.rb (0.5.3)
    listen (2.7.1)
      celluloid (>= 0.15.2)
      celluloid-io (>= 0.15.0)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    lumberjack (1.0.5)
    method_source (0.8.2)
    multi_json (1.9.2)
    nio4r (1.0.0)
    pry (0.9.12.6)
      coderay (~> 1.0)
      method_source (~> 0.8)
      slop (~> 3.4)
    rb-fsevent (0.9.4)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    slop (3.5.0)
    thor (0.19.1)
    timers (1.1.0)

PLATFORMS
  ruby

DEPENDENCIES
  guard
  guard-livereload

GuardFile

guard 'livereload' do
        watch(%r{kumbiaphp/default/app/views/.+\.(phtml)$})
	watch(%r{kumbiaphp/default/public/css/.+\.(css|js|html|phtml)})
	watch(%r{kumbiaphp/default/public/javascript/.+\.(css|js|html|phtml)})	
end

Thanks guys!

**Comment by e2** [comment]
I'm closing this since a lot has changed since this has opened.

If there's still a problem with a newer version of Guard, Listen (which at 3.x fixes the "terminating ..." problem) and Guard-Livereload, open a new issue.
