### ISSUE TITLE
Getting guard-livereload working with docker

### ISSUE THREAD

**Issue by cjroebuck** [guard/guard-livereload#116]
So I've almost got this working well through macosx -> vagrant -> docker. My rails app with guard runs via foreman in a docker container. I've forwarded the relevant ports from docker to vagrant and from vagrant to macosx. I'm using vagrants rsync shared folders with `vagrant rsync-auto` to sync filesystem changes.

I get the following error when running `bundle exec guard -d' and saving a watched file:

    00:38:04 guard.1   | 00:38:04 - DEBUG - Serving file /usr/local/lib/ruby/gems/2.0.0/gems/guard-livereload-2.3.0/js/livereload.js
    00:38:05 guard.1   | 00:38:05 - INFO - Browser connected.
    00:38:26 guard.1   | 00:38:26 - DEBUG - Trying to run Guard::LiveReload#run_on_additions with ["/assets/templates/index.emblem.erb"]
    00:38:26 guard.1   | 00:38:26 - DEBUG - Trying to run Guard::LiveReload#run_on_changes with ["/assets/templates/index.emblem.erb"]
    00:38:26 guard.1   | 00:38:26 - DEBUG - Trying to run     Guard::LiveReload#run_on_change with ["/assets/templates/index.emblem.erb"]
    00:38:27 guard.1   | 00:38:27 - DEBUG - Hook :run_on_modifications_begin executed for Guard::LiveReload
    00:38:27 guard.1   | 00:38:27 - INFO - Reloading browser: /assets/templates/index.emblem.erb
    00:38:27 guard.1   | 00:38:27 - DEBUG - {:command=>"reload", :path=>"/app//assets/templates/index.emblem.erb", :liveCSS=>true}
    00:38:27 guard.1   | 00:38:27 - DEBUG - Hook :run_on_modifications_end executed for Guard::LiveReload
    00:38:28 guard.1   | 00:38:28 - DEBUG - Serving file /usr/local/lib/ruby/gems/2.0.0/gems/guard-livereload-2.3.0/js/livereload.js
    00:38:28 guard.1   | 00:38:28 - DEBUG - Serving file /usr/local/lib/ruby/gems/2.0.0/gems/guard-livereload-2.3.0/js/livereload.js
    00:38:28 guard.1   | /usr/local/lib/ruby/gems/2.0.0/gems/guard-livereload-2.3.0/lib/guard/livereload/websocket.rb:12:in `<<': Could not parse data entirely (0 != 781) (HTTP::Parser::Error)
    00:38:28 guard.1   | 	from /usr/local/lib/ruby/gems/2.0.0/gems/guard-livereload-2.3.0/lib/guard/livereload/websocket.rb:12:in `dispatch'
    00:38:28 guard.1   | 	from /usr/local/lib/ruby/gems/2.0.0/gems/em-websocket-0.5.1/lib/em-websocket/connection.rb:78:in `receive_data'
    00:38:28 guard.1   | 	from /usr/local/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
    00:38:28 guard.1   | 	from     /usr/local/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
    00:38:28 guard.1   | 	from /usr/local/lib/ruby/gems/2.0.0/gems/guard-    livereload-2.3.0/lib/guard/livereload/reactor.rb:49:in `_start_reactor'
    00:38:28 guard.1   | 	from /usr/local/lib/ruby/gems/2.0.0/gems/guard-            livereload-2.3.0/lib/guard/livereload/reactor.rb:11:in `block in initialize'
    00:38:28 guard.1   | exited with code 1
    00:38:28 system    | sending SIGTERM to all processes

Strangely, without the `-d` flag, when I load the page, the browser reports a WebSocket error (connection closed before receiving a handshake response) and guard never actually reports that a browser connects.

If I change guard to run with `bundle exec guard -p -l 10` then the browser connects fine and it reloads on file changes .. although this causes CPU to max out and the time from saving a file to reloading it is quite long, so i'd love to get it working without relying on polling.

**Comment by e2** [comment]
I'm closing this. If this happens again, open a new issue and I'll add some extra debugs to work out what went wrong.

**Comment by aledalgrande** [comment]
For who comes here while dockerizing their Rails app, I just setup this sweet library (and the rack part) again and with success, after introducing docker.

```ruby
# in your development.rb
config.middleware.use(Rack::LiveReload, host: 'localhost', source: :vendored)
```

```yaml
# in your docker-compose.yml add this service
  livereload:
    build:
      # same build settings as your Rails app
    command: bundle exec guard -P livereload
    # [...] whatever else you need
    ports:
      - 35729:35729
    volumes:
      - .:/usr/app  # or however you configured your Rails root volume
```
