### ISSUE TITLE
Excluding files via regex doesnt work

### ISSUE THREAD

**Issue by noctivityinc** [guard/guard-livereload#117]
I am trying to make sure partials in rails arent being reloaded with this:

     watch(%r{app/views/[^_].+\.(erb|haml|slim)$})

but it doesnt seem to work.  Any thoughts?

**Comment by jibiel** [comment]
@noctivityinc the problem is in the regex you specified. It matches [both templates and partials](http://rubular.com/r/sHAWIC0NMM) as it stands. This one does the job (note the absence of `.` after `[^_]`):

```ruby
%r{app/views/[^_]+\.(erb|haml|slim)$}
```
Check it on the [Rubular](http://rubular.com/r/fUKDeIGH5k).

**Comment by thibaudgg** [comment]
@jibiel thanks for your comment!
