### ISSUE TITLE
How to use livereload on the remote server using putty

### ISSUE THREAD

**Issue by kargapoltsev** [guard/guard-livereload#121]
I've read the [article](http://feedback.livereload.com/knowledgebase/articles/86280-if-you-edit-files-directly-on-your-server), but I didn't find information how to connect to the server with the parameters
> ssh -L 35729:127.0.0.1:35729 ...

using Putty or other SSH client.

**Comment by jibiel** [comment]
@kargapoltsev I'm closing this issue in the absence of the activity, feel free to reopen it if you have any further questions.
