### ISSUE TITLE
"Could not connect to LiveReload server." -- rubygems library version (fixed in repo)

### ISSUE THREAD

**Issue by amites** [guard/guard-livereload#125]
Re-opening as #110 was closed without a solution

see issue link for previous examples of error & work arounds that work for some

**Comment by leandroruel** [comment]
same issue here since i download a fresh install 
error: **WebSocket connection to 'ws://127.0.0.1:35729/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED**

**Comment by amites** [comment]
fresh download from ```gem install``` or ```git clone``` ??

gem still has error, github seems to be fixed

**Comment by leandroruel** [comment]
from gem install
