### ISSUE TITLE
No reload after SCSS changes

### ISSUE THREAD

**Issue by ilyador** [guard/guard-livereload#126]
I have the following setup: rails 4. all SCSS and HTML are in `app/assets/stylesheets | templates`

Gemfile:
```
gem 'guard'
gem 'guard-compass'
gem 'guard-shell'
gem 'guard-livereload'
```

Guardfile:
```
guard :livereload do
  watch(%r{app/assets/.+\.(css|html|png|jpg)})
end
```

Liverload is connected and waiting for changes
```
$ guard
19:45:10 - INFO - LiveReload is waiting for a browser to connect.
19:45:11 - INFO - Guard is now watching at '/Users/dev/myproject'
[1] guard(main)> 19:46:05 - INFO - Browser connected.
```

**Comment by artm** [comment]
What extension do scss files have? Is it `.css.scss` (used to be the convention in rails < 4) or plain `.scss` (current convention)? 

The watch expression you quote will watch files with `.css` in their path and supply their exact relative path (barring possible extra stuff after `.css` to livereload, e.g. `"app/assets/stylesheets/navbar.css"`. But live reload plugin expects a path as browser would want it, e.g. `"/assets/navbar.css"`. 

I use the following to watch scss:

```ruby
guard :livereload do
  # ... more watch expressions skipped ...
  # watching pre rails 4 path convention conforming assets:
  watch(%r{(app|vendor)(/assets/\w+/(.+\.(css|js|html|png|jpg))).*}) { |m| "/assets/#{m[3]}" }
  # watching "modern" path convention assets:
  watch(%r{(app|vendor)(/assets/\w+/(.+)\.(scss))}) { |m| "/assets/#{m[3]}.css" }
end
```

both watch expressions convert asset source path to correct asset browser path, rack-livereload middleware takes care of the rest.

**Comment by soberstadt** [comment]
@artm's solution worked for me. Thanks man!

**Comment by e2** [comment]
The regexp got so complex, I've reworked the template (adding tests too): https://github.com/guard/guard-livereload/pull/146

Just open a new issue if something doesn't work on master.
