### ISSUE TITLE
Where is the package located? 

### ISSUE THREAD

**Issue by CrazySyntax** [guard/guard-livereload#171]
I followed the installation instructions.

I installed the gem by: 

`$ gem install guard-livereload
`

and now I have to edit the Gemfile. I tried to search for the path of the package guard-livereload and I couldn't find it. 
I typed: 
`$ dpkg -L guard-livereload-2.5.2
`
and got:

> dpkg-query: package 'guard-livereload-2.5.2' is not installed

I repeated "gem install" several times, and I every time I do it I get a message that installation is completed successfully, and again I can't find the package. 

Do you have an idea how to help me?

**Comment by dmitry** [comment]
@CrazySyntax just upgraded to the latest version:

```
    guard-livereload (2.5.2)
      em-websocket (~> 0.5)
      guard (~> 2.8)
      guard-compat (~> 1.0)
      multi_json (~> 1.8)
```

**Comment by dmitry** [comment]
Why you are using debian package manager, not rubygem?

**Comment by CrazySyntax** [comment]
mm.. I don't know. I do exactly what the instructions tell. 
Whay is the line you propose me to type?

**Comment by dmitry** [comment]
Just include `gem 'guard-livereload'` in your Gemfile, run `bundle install` and then execute `guard`,

**Comment by jibiel** [comment]
@CrazySyntax 

The installation process covered in the README — https://github.com/guard/guard-livereload#install.

`Gemfile` is usually a part of Ruby application (mostly Ruby on Rails app). You don't need it to use `guard-livereload` but you will definitely need `Guardfile`. Generate one by running:

```shell
$ guard init livereload
```

Please use our [Gitter chat](https://gitter.im/guard/guard-livereload?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for questions in the future.
