### ISSUE TITLE
CSS edits lose styling after reload

### ISSUE THREAD

**Issue by crobbo** [guard/guard-livereload#192]
Each time I make an edit to my CSS file I lose all styling. Whereas changing a HTML file works perfectly. 

Before CSS change:
![before_css_reload](https://user-images.githubusercontent.com/47796704/125686564-7468e966-4f6e-4f28-8bb4-5e90448d2da5.png)

After CSS change:
![after_reload](https://user-images.githubusercontent.com/47796704/125686617-1bbd0026-a47d-4e11-811a-b2cd9b24fabb.png)

**Comment by jamielife** [comment]
Why was this closed? Did you find a solution? I'm currently having the exactt same issue.

**Comment by crobbo** [comment]
> Why was this closed? Did you find a solution? I'm currently having the exactt same issue.

Sorry no, it's been a while since I used this gem!

**Comment by jamielife** [comment]
Ah, no worries. Should anybody help stumble upon this issue, I was able to find a work around that got it working on Windows. 

## Live Reload:

1. Add to project **Gemfile** (end of, group :development do)

```bash
gem 'guard-livereload', '~> 2.5', require: false
gem 'rack-livereload'
```

2. Console run:

```bash
bundle install
bundle exec guard init livereload
```

3. Add to config\environments\development.rb

```bash
#Live reloading
config.middleware.insert_after ActionDispatch::Static, Rack::LiveReload
config.assets.digest = false
```

4. Update Gaurdfile for CSS

```bash
watch(%r{(app|vendor)(/assets/\w+/(.+\.(css|js|html))).*}) { |m| "/assets/#{m[3]}" }
```

5. Run: 

```bash
rails s
Run: bundle exec guard (in new terminal tab)
```

6. In Windows Command Prompt (has to be cmd prompt, not git bash, etc.) run:

```bash
icacls tmp/cache /grant Everyone:F 
```
