### ISSUE TITLE
Error while installing guard-livereload

### ISSUE THREAD

**Issue by tariquesani** [guard/guard-livereload#66]
sudo gem install guard-livereload
Building native extensions.  This could take a while...
ERROR:  Error installing guard-livereload:
    ERROR: Failed to build gem native extension.
        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from extconf.rb:2:in `<main>'

I am running Ubuntu 12.10, any help would be appreciated

**Comment by jeka666** [comment]
Hello guys. Please help me with this error
pc:~$ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

pc:~$ sudo gem install guard-livereload
Building native extensions.  This could take a while...
ERROR:  Error installing guard-livereload:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... yes
checking for ruby/thread.h... no
checking for inotify_init() in sys/inotify.h... yes
checking for writev() in sys/uio.h... yes
checking for rb_thread_fd_select()... yes
checking for rb_fdset_t in ruby/intern.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... yes
checking for rb_time_new()... yes
checking for sys/event.h... no
checking for epoll_create() in sys/epoll.h... yes
checking for clock_gettime()... yes
checking for CLOCK_MONOTONIC_RAW in time.h... yes
checking for CLOCK_MONOTONIC in time.h... yes
creating Makefile

make
compiling ssl.cpp
compiling cmain.cpp
compiling ed.cpp
ed.cpp: In member function ‘void EventableDescriptor::_GenericInboundDispatch(const char*, int)’:
ed.cpp:305:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (proxied < size) {
                   ^
compiling rubymain.cpp
compiling kb.cpp
kb.cpp: In member function ‘virtual void KeyboardDescriptor::Read()’:
kb.cpp:77:27: warning: ignoring return value of ‘ssize_t read(int, void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
  read (GetSocket(), &c, 1);
                           ^
compiling em.cpp
In file included from project.h:50:0,
                 from em.cpp:23:
em.cpp: In member function ‘void EventMachine_t::_ReadInotifyEvents()’:
em.cpp:2273:44: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
   assert(!(returned == 0 || returned == -1 && errno == EINVAL));
                                            ^
em.cpp: In member function ‘void EventMachine_t::SignalLoopBreaker()’:
em.cpp:312:34: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
  write (LoopBreakerWriter, "", 1);
                                  ^
em.cpp: In member function ‘void EventMachine_t::_ReadLoopBreaker()’:
em.cpp:1085:50: warning: ignoring return value of ‘ssize_t read(int, void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
  read (LoopBreakerReader, buffer, sizeof(buffer));
                                                  ^
compiling binder.cpp
compiling pipe.cpp
compiling page.cpp
linking shared-object rubyeventmachine.so
/usr/bin/ld: /usr/local/lib/libssl.a(s23_srvr.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libssl.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [rubyeventmachine.so] Error 1


Gem files will remain installed in /var/lib/gems/1.9.1/gems/eventmachine-1.0.7 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/eventmachine-1.0.7/ext/gem_make.out

**Comment by CrazySyntax** [comment]
I also get: 

> Building native extensions.  This could take a while...
> ERROR:  Error installing guard-livereload:
> 	ERROR: Failed to build gem native extension.
> 
>     current directory: /var/lib/gems/2.3.0/gems/ffi-1.9.14/ext/ffi_c
> /usr/bin/ruby2.3 -r ./siteconf20161023-850-73hif2.rb extconf.rb
> mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

after typing:
$ sudo gem install guard-livereload

I read this thread and I installed build-essential. Still, it didn't solve this problem.

**Comment by maosan132** [comment]
> > make: g++: Command not found
> 
> You need to install a compiler in order to comple the native extension, e.g.
> 
> ```
> $ sudo apt-get install build-essential 
> ```

It worked! (Ubuntu 18, ruby 2.6, rails 5.2.3)
