### ISSUE TITLE
Guard live-reload not detecting changes to SCSS partials

### ISSUE THREAD

**Issue by mattymess** [guard/guard-livereload#76]
I use the underscore filename convention for my SCSS partials (_buttons.css.scss), but guard-livereload isn't detecting changes to these files. If I make a change to my main SCSS file that does all the importing (application.css.scss), livereload works like a charm. 

I'm assuming I need to adjust the regex in the Guardfile, but I just don't know regex that well. I really don't have to have to change my filename conventions to make this work. Can someone assist? Here's my Guardfile...

``` guardfile
guard 'livereload' do
  watch(%r{app/views/.+\.(erb|haml|slim)$})
  watch(%r{app/helpers/.+\.rb})
  watch(%r{public/.+\.(css|js|html)})
  watch(%r{config/locales/.+\.yml})
  # Rails Assets Pipeline
  watch(%r{(app|vendor)(/assets/\w+/(.+\.(css|js|html))).*}) { |m| "/assets/#{m[3]}" }
end
```

**Comment by joeosburn** [comment]
Using @ehsanul's line along with a standard line seems to provide pretty good coverage of all potential file types:

  watch(%r{(app|vendor)(/assets/\w+/.+)\.s(c|a)ss}) { |m| "#{m[2]}.css" } # sass files
  watch(%r{(app|vendor)(/assets/\w+/(.+\.(css|js|html|png|jpg))).*}) { |m| "/assets/#{m[3]}" }

**Comment by michaelkoper** [comment]
Thanks @thibaudgg and @chrishough. You guys are life savers!!

**Comment by joallard** [comment]
I made this one for both `<file>.css.s[ac]ss` files and `<file>.s[ac]ss`:
```rb
  watch(%r{(app|vendor)(/assets/\w+/.+?)(?:\.css)?.s[ac]ss}){ |m| "#{m[2]}.css" }
```

**Comment by e2** [comment]
@joallard - the `Guardfile` template was recently updated, so check if it works already: https://github.com/guard/guard-livereload/blob/master/lib/guard/livereload/templates/Guardfile

**Comment by jacobjlevine** [comment]
@e2 that was the perfect suggestion. Just updated my Guardfile to reflect the new template and it solved the issue @LeBenLeBen described with the .scss files not being handled properly.
