### ISSUE TITLE
Please add the following to your Gemfile to avoid polling for changes ...

### ISSUE THREAD

**Issue by flashios09** [guard/guard-livereload#87]
Hi,
Sorry for my bad english :)
I formatted my PC and reinstalled WIN8 32 bit. 
Before guard works correclty and i can compile sass, livereload my page, concat and minify js but now livereload doesn't work any more :(
thats a screenshot 
![guard-error](https://f.cloud.github.com/assets/1313482/1384274/e688ae40-3b4a-11e3-9139-aa5422223196.jpg)

I installed ruby via rubyinstaller 1.9.3-p448 , 
guard(gem install guard), 
guard-compass(gem install guard-compass), 
guard-livereload(gem install guard-livereload), 
guard-uglify(gem install guard-uglify), 
guard-concat(gem install guard-concat) 

what i have to do ?
thanks

**Comment by thexphi** [comment]
I had the same problem. I add `  gem 'wdm', '~> 0.1.0'` into the `Gemfile`  and the problem was solved. Thank @netzpirat for your post.
